import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blogging Webpage",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex h-[90vh]">
          {/* Left Section */}
          <main className="w-[70%] border-r border-gray-300 overflow-y-auto custom-scrollbar p-4">{children}</main>

          {/* Right Section */}
          <div className="w-[30%] p-4 overflow-y-auto">
            <h2 className="text-lg font-bold mb-4">Blog Titles</h2>
            <ul className="space-y-2">
              {/* Render your blog titles dynamically */}
              <li className="text-gray-700">Blog Title 1</li>
              <li className="text-gray-700">Blog Title 2</li>
              <li className="text-gray-700">Blog Title 3</li>
              {/* Add more titles here */}
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
